//
// Created by paulkokos on 9/27/2020.
//

#ifndef ARTIFICIALINTELIGENCELIBRARY_ALGORITHMS_HPP
#define ARTIFICIALINTELIGENCELIBRARY_ALGORITHMS_HPP


class Algorithms {

};


#endif //ARTIFICIALINTELIGENCELIBRARY_ALGORITHMS_HPP
