//
// Created by paulkokos on 9/27/2020.
//

#ifndef ARTIFICIALINTELIGENCELIBRARY_ARTIFICIALINTELLIGENCE_HPP
#define ARTIFICIALINTELIGENCELIBRARY_ARTIFICIALINTELLIGENCE_HPP


class ArtificialIntelligence {

};


#endif //ARTIFICIALINTELIGENCELIBRARY_ARTIFICIALINTELLIGENCE_HPP
