//
// Created by paulkokos on 9/28/2020.
//

#ifndef ARTIFICIALINTELIGENCELIBRARY_CLASSIFICATION_HPP
#define ARTIFICIALINTELIGENCELIBRARY_CLASSIFICATION_HPP


class Classification : public Math{

};


#endif //ARTIFICIALINTELIGENCELIBRARY_CLASSIFICATION_HPP
